import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { useSecureImage } from "@/hooks/useSecureImage";
import { Loader2, AlertTriangle } from "lucide-react";

interface DebugAssets {
  raw_mask_url?: string;
  expanded_mask_url?: string;
}

interface DebugStepsModalProps {
  isOpen: boolean;
  onClose: () => void;
  assets: DebugAssets | null;
}

const ImageCard = ({ title, url }: { title: string, url?: string }) => {
  const { displayUrl, isLoading, error } = useSecureImage(url);
  return (
    <div className="space-y-2">
      <h3 className="text-sm font-semibold text-center">{title}</h3>
      <div className="aspect-square bg-muted rounded-md flex items-center justify-center overflow-hidden">
        {!url ? <p className="text-xs text-muted-foreground">Not available</p> :
         isLoading ? <Loader2 className="h-8 w-8 animate-spin" /> :
         error ? <AlertTriangle className="h-8 w-8 text-destructive" /> :
         displayUrl ? <img src={displayUrl} alt={title} className="max-w-full max-h-full object-contain" /> : null
        }
      </div>
    </div>
  );
};

export const DebugStepsModal = ({ isOpen, onClose, assets }: DebugStepsModalProps) => {
  if (!isOpen || !assets) return null;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Segmentation Mask Debug</DialogTitle>
          <DialogDescription>
            A comparison of the raw mask generated by the AI and the expanded version used for inpainting.
          </DialogDescription>
        </DialogHeader>
        <div className="grid grid-cols-2 gap-4 py-4">
          <ImageCard title="Raw Combined Mask" url={assets.raw_mask_url} />
          <ImageCard title="Expanded Mask (Used)" url={assets.expanded_mask_url} />
        </div>
      </DialogContent>
    </Dialog>
  );
};