import { useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Download, Wand2, Loader2 } from "lucide-react";
import { downloadImage } from "@/lib/utils";
import { useSession } from "./Auth/SessionContextProvider";
import { showError, showLoading, dismissToast, showSuccess } from "@/utils/toast";
import { useLanguage } from "@/context/LanguageContext";
import { translations } from "@/lib/i18n";

interface PreviewData {
  url: string;
  jobId?: string;
}

interface ImagePreviewModalProps {
  data: PreviewData | null;
  onClose: () => void;
}

export const ImagePreviewModal = ({ data, onClose }: ImagePreviewModalProps) => {
  const { supabase } = useSession();
  const { language } = useLanguage();
  const t = translations[language];
  const [isUpscaling, setIsUpscaling] = useState(false);

  if (!data) return null;

  const handleDownload = () => {
    const filename = data.url.split('/').pop() || 'download.png';
    downloadImage(data.url, filename);
  };

  const handleUpscaleAndDownload = async (factor: number) => {
    if (!data.jobId) {
      showError("Upscaling is only available for images generated by the agent.");
      return;
    }
    setIsUpscaling(true);
    const toastId = showLoading(`Upscaling image x${factor}...`);
    try {
      const { data: result, error } = await supabase.functions.invoke('MIRA-AGENT-tool-upscale-image-clarity', {
        body: { image_url: data.url, job_id: data.jobId, upscale_factor: factor }
      });

      if (error) throw error;
      
      const newUrl = result.upscaled_image.url;
      if (!newUrl) throw new Error("Upscaler did not return a valid image URL.");

      const originalFilename = data.url.split('/').pop()?.split('.')[0] || 'image';
      downloadImage(newUrl, `upscaled_${factor}x_${originalFilename}.png`);
      showSuccess("Upscaled image is downloading!");

    } catch (err: any) {
      showError(`Upscale failed: ${err.message}`);
    } finally {
      dismissToast(toastId);
      setIsUpscaling(false);
    }
  };

  return (
    <Dialog open={!!data.url} onOpenChange={(isOpen) => !isOpen && onClose()}>
      <DialogContent className="max-w-4xl p-2">
        <DialogTitle className="sr-only">Image Preview</DialogTitle>
        <DialogDescription className="sr-only">A larger view of the selected image. You can download or upscale it from the button in the top right corner.</DialogDescription>
        <div className="relative">
          <img key={data.url} src={data.url} alt="Preview" className="max-h-[90vh] w-full object-contain rounded-md" />
          <div className="absolute top-4 right-4">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="secondary" size="icon">
                  {isUpscaling ? <Loader2 className="h-4 w-4 animate-spin" /> : <Wand2 className="h-4 w-4" />}
                  <span className="sr-only">Image Actions</span>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem onSelect={handleDownload}>
                  <Download className="mr-2 h-4 w-4" />
                  {t.download}
                </DropdownMenuItem>
                <DropdownMenuItem onSelect={() => handleUpscaleAndDownload(2)} disabled={!data.jobId || isUpscaling}>
                  {t.upscaleAndDownload} x2
                </DropdownMenuItem>
                <DropdownMenuItem onSelect={() => handleUpscaleAndDownload(3)} disabled={!data.jobId || isUpscaling}>
                  {t.upscaleAndDownload} x3
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};