// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ukxguvvbgjvukrsdnxmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVreGd1dnZiZ2p2dWtyc2RueG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NDM0NDcsImV4cCI6MjA2MTExOTQ0N30.KtJkyH9TW_KhLUIKMyHtVMNi3gqDX2Vz20UaFSta0-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);