import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient, SupabaseClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0';
import { GoogleGenAI, Type, FunctionDeclaration, Content, Part, GenerationResult } from 'https://esm.sh/@google/genai@0.15.0';
import { encodeBase64 } from "https://deno.land/std@0.224.0/encoding/base64.ts";

const SUPABASE_URL = Deno.env.get('SUPABASE_URL');
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY');
const MODEL_NAME = "gemini-2.5-pro-preview-06-05";
const UPLOAD_BUCKET = "mira-agent-user-uploads";
const GENERATED_IMAGES_BUCKET = 'mira-generations';
const MAX_RETRIES = 3;
const RETRY_DELAY_MS = 1000;

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const modelAspectRatioMap: any = {
    openai: ['1024x1024', '1024x1536', '1536x1024'],
    google: ['1024x1024', '768x1408', '1408x768', '1280x896', '896x1280'],
    'fal-ai': ['1:1', '16:9', '21:9', '2:3', '3:2', '3:4', '4:3', '9:16', '9:21'],
};

const getDynamicSystemPrompt = (jobContext: any): string => {
    const basePrompt = `You are Mira, a master AI orchestrator. Your job is to create and execute a multi-step plan to fulfill the user's request. You will be given the full history of the conversation. Your response MUST ALWAYS be a tool call.

**Core Planning Logic:**
1.  **Analyze Intent:**
    -   If the user provides an image, you MUST assume it is for style, composition, or subject reference. Your ONLY valid first step is to call \`dispatch_to_artisan_engine\`.
    -   If the request is text-only, proceed to the Text-to-Image Workflow.
    -   If the request is conversational or ambiguous, use \`finish_task\` to ask for clarification.

2.  **Text-to-Image Workflow:**
    a. **Creative Loop:** Initiate the self-correction loop: \`dispatch_to_artisan_engine\` -> \`generate_image\` -> \`critique_images\`. Repeat this loop until the critique returns \`is_good_enough: true\`.
    b. **Refinement Check:** After an image is approved by the critique, you MUST follow the specific refinement rule provided below.`;

    const pipelineMode = jobContext?.pipelineMode || 'auto';
    let refinementRule = '';

    switch (pipelineMode) {
        case 'on':
            refinementRule = `
    **Refinement Rule (Mode: ON):** You MUST now proceed to the Final Refinement Step by calling the \`fal_image_to_image\` tool. There are no exceptions. Pass all publicUrls from the previously generated image batch to the tool.`;
            break;
        case 'off':
            refinementRule = `
    **Refinement Rule (Mode: OFF):** The plan is now complete. You MUST call \`finish_task\`.`;
            break;
        case 'auto':
        default:
            refinementRule = `
    **Refinement Rule (Mode: AUTO):** You MUST check the model ID used in the last \`generate_image\` call. If the model ID contains 'gpt' or 'imagen', proceed to the Final Refinement Step by calling \`fal_image_to_image\`. For all other models (like FLUX), the plan is complete and you MUST call \`finish_task\`.`;
            break;
    }

    const finalPrompt = `${basePrompt}${refinementRule}
    c. **Final Refinement Step:** Call the \`fal_image_to_image\` tool. You MUST find the most recent prompt generated by the \`ArtisanEngine\` in the conversation history and pass that as the \`prompt\` argument. You MUST pass all publicUrls from the previously generated image batch to the \`image_urls\` parameter.
    d. **Completion:** After the refinement step (or if it was skipped), the plan is complete. Call \`finish_task\` with the final image batch.

You MUST NOT answer the user directly. Your only output is a tool call.`;
    
    console.log(`[MasterWorker] Using dynamic system prompt for pipeline_mode: '${pipelineMode}'`);
    return finalPrompt;
};


async function getDynamicMasterTools(jobContext: any, supabase: SupabaseClient): Promise<FunctionDeclaration[]> {
    const baseTools: FunctionDeclaration[] = [
      { name: "dispatch_to_artisan_engine", description: "Generates or refines a detailed image prompt. This is the correct first step if the user provides a reference image.", parameters: { type: Type.OBJECT, properties: { user_request_summary: { type: Type.STRING, description: "A brief summary of the user's request for the Artisan Engine, noting that a reference image was provided for style/composition." } }, required: ["user_request_summary"] } },
      { name: "fal_image_to_image", description: "Refines a batch of images using a secondary AI model.", parameters: { type: Type.OBJECT, properties: { image_urls: { type: Type.ARRAY, items: { type: Type.STRING }, description: "An array of public URLs of the images to be refined." }, prompt: { type: Type.STRING, description: "The detailed prompt from the ArtisanEngine to guide the refinement." } }, required: ["image_urls", "prompt"] } },
      { name: "critique_images", description: "Invokes the Art Director agent to critique generated images.", parameters: { type: Type.OBJECT, properties: { reason_for_critique: { type: Type.STRING, description: "A brief summary of why the critique is necessary." } }, required: ["reason_for_critique"] } },
      { name: "finish_task", description: "Call this to respond to the user.", parameters: { type: Type.OBJECT, properties: { response_type: { type: Type.STRING, enum: ["clarification_question", "creative_process_complete", "text"], description: "The type of response to send." }, summary: { type: Type.STRING, description: "The message to send to the user." }, follow_up_message: { type: Type.STRING, description: "A helpful follow-up message." } }, required: ["response_type", "summary"] } },
    ];

    let selectedModelId = jobContext?.selectedModelId;
    let provider = 'openai';
    let supportsImg2Img = false;

    if (selectedModelId) {
        const { data, error } = await supabase.from('mira-agent-models').select('provider, supports_img2img').eq('model_id_string', selectedModelId).single();
        if (error) {
            console.warn(`Could not fetch provider for ${selectedModelId}, defaulting to 'openai'. Error: ${error.message}`);
        } else {
            provider = data.provider.toLowerCase().replace(/\s/g, '-');
            supportsImg2Img = data.supports_img2img;
        }
    }
    
    const validSizes = modelAspectRatioMap[provider] || modelAspectRatioMap.openai;

    const generateImageTool: FunctionDeclaration = {
        name: "generate_image",
        description: "Generates images based on a given TEXT-ONLY prompt and various parameters.",
        parameters: {
            type: Type.OBJECT,
            properties: {
                prompt: { type: Type.STRING, description: "The detailed, final prompt to be used for image generation." },
                size: { type: Type.STRING, description: "The desired image dimensions, formatted as 'WIDTHxHEIGHT' for Google/OpenAI or 'W:H' for Fal.ai.", enum: validSizes },
                number_of_images: { type: Type.NUMBER, description: "The number of images to generate." },
                model_id: { type: Type.STRING, description: "The specific model ID to use for generation." },
                negative_prompt: { type: Type.STRING, description: "A description of what to avoid in the image." },
                seed: { type: Type.NUMBER, description: "A seed for deterministic generation." }
            },
            required: ["prompt"]
        }
    };
    
    const allTools = [generateImageTool, ...baseTools];

    const hasReferenceImage = jobContext?.user_provided_assets?.some((asset: any) => asset.type === 'image');
    if (hasReferenceImage && supportsImg2Img) {
        console.log(`[MasterWorker] Context has reference image and model supports img2img. Adding 'generate_image_with_reference' tool.`);
        const generateWithReferenceTool: FunctionDeclaration = {
            name: "generate_image_with_reference",
            description: "Generates an image using a user-provided reference image and a text prompt. Only use this if the user has uploaded an image.",
            parameters: {
                type: Type.OBJECT,
                properties: {
                    prompt: { type: Type.STRING, description: "A text prompt that describes the desired modifications or the scene for the reference image." },
                    model_id: { type: Type.STRING, description: "The specific model ID to use for generation." },
                    aspect_ratio: { type: Type.STRING, description: "The desired aspect ratio, e.g., '1:1', '16:9'." }
                },
                required: ["prompt"]
            }
        };
        allTools.push(generateWithReferenceTool);
    }

    return allTools;
}

function getMimeType(filePath: string): string | null {
    const extension = filePath.split('.').pop()?.toLowerCase();
    if (!extension) return null;

    switch (extension) {
        case 'png': return 'image/png';
        case 'jpg':
        case 'jpeg': return 'image/jpeg';
        case 'webp': return 'image/webp';
        case 'gif': return 'image/gif';
        case 'pdf': return 'application/pdf';
        case 'txt': return 'text/plain';
        default: return null;
    }
}

serve(async (req) => {
  if (req.method === 'OPTIONS') { return new Response(null, { headers: corsHeaders }); }
  
  const { job_id, prompt, storagePaths, userId, isDesignerMode, pipelineMode, selectedModelId } = await req.json();
  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
  let currentJobId = job_id;

  try {
    if (!currentJobId) {
      console.log("[MasterWorker] Received new request. Creating job...");
      if (!prompt) throw new Error("A 'prompt' is required for new jobs.");
      if (!userId) throw new Error("A 'userId' is required for new jobs.");

      const userParts: Part[] = [{ text: prompt }];
      const userProvidedAssets: any[] = [];

      if (storagePaths && Array.isArray(storagePaths)) {
          for (const path of storagePaths) {
              const mimeType = getMimeType(path);
              if (mimeType) {
                  const { data: fileBlob, error: downloadError } = await supabase.storage.from(UPLOAD_BUCKET).download(path);
                  if (downloadError) throw new Error(`Failed to download file from storage: ${downloadError.message}`);
                  const arrayBuffer = await fileBlob.arrayBuffer();
                  const base64String = encodeBase64(arrayBuffer);
                  const originalName = path.split('/').pop();
                  userParts.push({ inlineData: { mimeType: mimeType, data: base64String, name: originalName } });
                  userProvidedAssets.push({ type: 'image', storagePath: path, originalName: originalName });
              }
          }
      }
      
      console.log(`[MasterWorker] Creating Asset Manifest with ${userProvidedAssets.length} items.`);

      const { data: newJob, error: createError } = await supabase
        .from('mira-agent-jobs')
        .insert({ 
            original_prompt: prompt, 
            status: 'processing', 
            user_id: userId,
            context: { 
                history: [{ role: "user", parts: userParts }], 
                user_provided_assets: userProvidedAssets,
                iteration_number: 1,
                safety_retry_count: 0,
                isDesignerMode: isDesignerMode,
                pipelineMode: pipelineMode,
                selectedModelId: selectedModelId
            } 
        })
        .select()
        .single();
      
      if (createError) throw createError;
      currentJobId = newJob.id;
      console.log(`[MasterWorker][${currentJobId}] Job created successfully for user ${userId}.`);
      
      console.log(`[MasterWorker][${currentJobId}] Invoking chat titler in the background...`);
      supabase.functions.invoke('MIRA-AGENT-tool-generate-chat-title', {
        body: { job_id: currentJobId, user_parts: userParts }
      }).catch(err => console.error(`[MasterWorker][${currentJobId}] Error invoking chat titler:`, err));

      console.log(`[MasterWorker][${currentJobId}] Kicking off main job processing...`);
      supabase.functions.invoke('MIRA-AGENT-master-worker', { body: { job_id: currentJobId } }).catch(console.error);
      return new Response(JSON.stringify({ reply: { type: 'job_started', jobId: currentJobId, message: "Thinking..." } }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }

    console.log(`[MasterWorker][${currentJobId}] Continuing job...`);
    const { data: job, error: fetchError } = await supabase.from('mira-agent-jobs').select('*').eq('id', currentJobId).single();
    if (fetchError) throw fetchError;

    const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
    let history: Content[] = job.context?.history || [];
    let iterationNumber = job.context?.iteration_number || 1;
    
    console.log(`[MasterWorker][${currentJobId}] History has ${history.length} turns. Iteration: ${iterationNumber}. Preparing to send to Gemini planner.`);
    
    const dynamicTools = await getDynamicMasterTools(job.context, supabase);
    const systemPrompt = getDynamicSystemPrompt(job.context);

    let result: GenerationResult | null = null;
    for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
      try {
        console.log(`[MasterWorker][${currentJobId}] Calling Gemini planner, attempt ${attempt}...`);
        result = await ai.models.generateContent({
          model: MODEL_NAME,
          contents: history,
          config: { systemInstruction: { role: "system", parts: [{ text: systemPrompt }] }, tools: [{ functionDeclarations: dynamicTools }] }
        });
        break;
      } catch (error) {
        console.warn(`[MasterWorker][${currentJobId}] Planner attempt ${attempt} failed:`, error.message);
        if (attempt === MAX_RETRIES) throw error;
        await new Promise(resolve => setTimeout(resolve, RETRY_DELAY_MS));
      }
    }

    if (!result) throw new Error("AI planner failed to respond after all retries.");

    const functionCalls = result.functionCalls;
    if (!functionCalls || functionCalls.length === 0) throw new Error("Orchestrator did not return a tool call.");

    const call = functionCalls[0];
    console.log(`[MasterWorker][${currentJobId}] Gemini decided to call tool: ${call.name} with args:`, call.args);
    history.push({ role: 'model', parts: [{ functionCall: call }] });
    
    let toolResponseData;
    const historyParts: Part[] = [];

    if (call.name === 'generate_image_with_reference') {
        console.log(`[MasterWorker][${currentJobId}] Dispatching to image-to-image tool...`);
        const { model_id } = call.args;
        const finalModelId = model_id || job.context?.selectedModelId;
        const { data: modelDetails } = await supabase.from('mira-agent-models').select('provider').eq('model_id_string', finalModelId).single();
        const provider = modelDetails?.provider.toLowerCase().replace(/\s/g, '-') || 'openai';

        const payload: any = { ...call.args, invoker_user_id: job.user_id };
        const asset = job.context?.user_provided_assets?.[0];
        if (asset && asset.storagePath) {
            console.log(`[MasterWorker][${currentJobId}] Found asset: ${asset.storagePath}. Downloading and encoding...`);
            const { data: fileBlob, error: downloadError } = await supabase.storage.from(UPLOAD_BUCKET).download(asset.storagePath);
            if (downloadError) throw new Error(`Failed to download reference asset: ${downloadError.message}`);
            const arrayBuffer = await fileBlob.arrayBuffer();
            payload.reference_image = {
                data: encodeBase64(arrayBuffer),
                mimeType: getMimeType(asset.storagePath) || 'image/png'
            };
        } else {
            throw new Error("Planner requested to use a reference image, but none was found in the job's asset manifest.");
        }
        
        let toolToInvoke = '';
        if (provider === 'openai') {
            toolToInvoke = 'MIRA-AGENT-tool-openai-image-edit';
        } else if (provider === 'fal.ai') {
            toolToInvoke = 'MIRA-AGENT-tool-fal-flux-unified';
        } else {
            throw new Error(`Provider '${provider}' does not support image-to-image generation.`);
        }

        console.log(`[MasterWorker][${currentJobId}] Invoking img2img tool: ${toolToInvoke}`);
        const { data, error } = await supabase.functions.invoke(toolToInvoke, { body: payload });
        if (error) throw error;
        toolResponseData = data;
        historyParts.push({ functionResponse: { name: call.name, response: toolResponseData } });

    } else if (call.name === 'generate_image') {
        console.log(`[MasterWorker][${currentJobId}] Dispatching to text-to-image generator...`);
        const { model_id } = call.args;
        let finalModelId = model_id || job.context?.selectedModelId;

        if (!finalModelId) {
            const { data: dbModel, error: modelError } = await supabase.from('mira-agent-models').select('model_id_string').eq('model_type', 'image').eq('is_default', true).single();
            if (modelError) throw new Error(`Failed to fetch default image model: ${modelError.message}`);
            finalModelId = dbModel.model_id_string;
        }

        const { data: modelDetails, error: modelDetailsError } = await supabase.from('mira-agent-models').select('provider').eq('model_id_string', finalModelId).maybeSingle();
        if (modelDetailsError) throw modelDetailsError;

        let provider;
        if (modelDetails) {
            provider = modelDetails.provider.toLowerCase().replace(/\s/g, '-');
        } else {
            provider = 'openai'; // Fallback
        }
        
        let toolToInvoke = '';
        switch (provider) {
            case 'google': toolToInvoke = 'MIRA-AGENT-tool-generate-image-google'; break;
            case 'fal.ai': toolToInvoke = 'MIRA-AGENT-tool-fal-flux-unified'; break;
            case 'openai': toolToInvoke = 'MIRA-AGENT-tool-openai-image-generate'; break;
            default: throw new Error(`Unknown provider '${provider}' for image generation.`);
        }

        console.log(`[MasterWorker][${currentJobId}] Provider is '${provider}'. Invoking tool: ${toolToInvoke}`);
        const { data, error } = await supabase.functions.invoke(toolToInvoke, { body: { ...call.args, model_id: finalModelId, invoker_user_id: job.user_id } });
        if (error) throw error;
        toolResponseData = data;
        
        if (toolResponseData.error === 'moderation_blocked') {
            let retryCount = job.context.safety_retry_count || 0;
            if (retryCount < 2) {
                retryCount++;
                console.log(`[MasterWorker][${currentJobId}] Safety system blocked generation. Attempting retry #${retryCount}.`);
                const retryHistory: Content[] = [
                    ...history,
                    { role: 'function', parts: [{ functionResponse: { name: call.name, response: toolResponseData } }] },
                    { role: 'model', parts: [{ text: "The previous attempt was blocked by the safety system. I will now ask the Artisan to create a safer version of the prompt." }] },
                    { role: 'model', parts: [{ functionCall: { name: 'dispatch_to_artisan_engine', args: { user_request_summary: 'The previous prompt was blocked by safety filters. Please generate a new, safer version of the prompt that avoids potentially sensitive topics.' } } }] }
                ];
                await supabase.from('mira-agent-jobs').update({ context: { ...job.context, history: retryHistory, safety_retry_count: retryCount } }).eq('id', currentJobId);
                supabase.functions.invoke('MIRA-AGENT-master-worker', { body: { job_id: currentJobId } });
                return new Response(JSON.stringify({ success: true, message: "Safety error detected, initiating retry." }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
            } else {
                throw new Error("Image generation failed after 2 retries due to safety system blocks.");
            }
        }
        historyParts.push({ functionResponse: { name: call.name, response: toolResponseData } });

    } else if (call.name === 'fal_image_to_image') {
        console.log(`[MasterWorker][${currentJobId}] Dispatching to Fal.ai image-to-image tool...`);
        const payload = { ...call.args, invoker_user_id: job.user_id };
        const { data, error } = await supabase.functions.invoke('MIRA-AGENT-tool-fal-image-to-image', { body: payload });
        if (error) throw error;
        toolResponseData = data;
        historyParts.push({ functionResponse: { name: call.name, response: toolResponseData } });

    } else if (call.name === 'dispatch_to_artisan_engine' || call.name === 'critique_images') {
        const toolName = call.name === 'dispatch_to_artisan_engine' ? 'MIRA-AGENT-tool-generate-image-prompt' : 'MIRA-AGENT-tool-critique-images';
        console.log(`[MasterWorker][${currentJobId}] Invoking ${toolName}...`);
        const { data, error } = await supabase.functions.invoke(toolName, { body: { history: history, iteration_number: iterationNumber, is_designer_mode: job.context?.isDesignerMode } });
        if (error) throw error;
        toolResponseData = data;
        historyParts.push({ functionResponse: { name: call.name, response: toolResponseData } });

        if (call.name === 'critique_images' && data.is_good_enough === false) {
            iterationNumber++;
            console.log(`[MasterWorker][${currentJobId}] Critique rejected. Incrementing iteration to ${iterationNumber}.`);
        }
    } else if (call.name === 'finish_task') {
        const { response_type, summary, follow_up_message } = call.args;
        let finalResult;
        let finalStatus = 'complete';

        console.log(`[MasterWorker][${currentJobId}] Finish task called with type: ${response_type}.`);
        if (response_type === 'creative_process_complete') {
            finalResult = { isCreativeProcess: true }; // Simple flag, UI will parse the history
        } else {
            finalResult = { text: summary };
        }
        
        if (response_type === 'clarification_question') {
            finalStatus = 'awaiting_feedback';
        }
        
        if (follow_up_message) finalResult.follow_up_message = follow_up_message;

        await supabase.from('mira-agent-jobs').update({ status: finalStatus, final_result: finalResult, context: { ...job.context, history, iteration_number: iterationNumber } }).eq('id', currentJobId);
        console.log(`[MasterWorker][${currentJobId}] Job status set to '${finalStatus}'. Job is complete.`);
        return new Response(JSON.stringify({ success: true }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    } else {
      throw new Error(`Master worker received unknown tool call: ${call.name}`);
    }
    
    history.push({ role: 'function', parts: historyParts });
    await supabase.from('mira-agent-jobs').update({ context: { ...job.context, history: history, iteration_number: iterationNumber }, status: 'processing' }).eq('id', currentJobId);
    
    console.log(`[MasterWorker][${currentJobId}] Step complete. Invoking next step...`);
    // Fire-and-forget the next invocation
    supabase.functions.invoke('MIRA-AGENT-master-worker', { body: { job_id: currentJobId } });
    
    return new Response(JSON.stringify({ success: true }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });

  } catch (error) {
    console.error(`[MasterWorker] FATAL ERROR for job ${currentJobId}:`, error);
    if (currentJobId) await supabase.from('mira-agent-jobs').update({ status: 'failed', error_message: error.message }).eq('id', currentJobId);
    return new Response(JSON.stringify({ error: error.message }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 });
  }
});